version: '3.7'

services:
  # images:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   working_dir: /code
  #   volumes:
  #     - ".:/code"
  #   entrypoint: ["sh", "-c", "sleep infinity"]
  
  ddnb-nodejs:
    container_name: ddnb-nodejs
    image: ddnb/nodejs:latest
    init: true
    tty: true
    stdin_open: true
    volumes:
      - ./code:/code
    working_dir: /code
    env_file:
      - .env
    entrypoint: ["sh", "-c", "sleep infinity"] 